version: "3.8"

networks:
  contextify-net:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    networks:
      - contextify-net
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_4LW_COMMANDS_WHITELIST=*
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    networks:
      - contextify-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --bootstrap-server localhost:9092 --list",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15
    container_name: contextify-postgres
    networks:
      - contextify-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: contextify
      POSTGRES_PASSWORD: contextify
      POSTGRES_DB: contextify
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contextify"]
      interval: 5s
      retries: 5

  contextify:
    container_name: contextify
    build:
      context: ../backend
      dockerfile: services/contextify/Dockerfile
    networks:
      - contextify-net
    ports:
      - "8082:8080"
      - "50051:50051"
    environment:
      - REST_PORT=8080
      - GRPC_PORT=50051
      - KAFKA_BROKERS=kafka:9092
      - DATABASE_URL=postgres://contextify:contextify@postgres:5432/contextify?sslmode=disable
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

  anomaly:
    container_name: anomaly
    build:
      context: ../backend
      dockerfile: services/anomaly/Dockerfile
    networks:
      - contextify-net
    ports:
      - "8081:8081"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - DATABASE_URL=postgres://contextify:contextify@postgres:5432/contextify?sslmode=disable
      - HTTP_PORT=8081
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

  anomaly-producer:
    container_name: anomaly-producer
    build:
      context: ../backend
      dockerfile: services/anomaly/Dockerfile.producer
    networks:
      - contextify-net
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKERS=kafka:9092
    restart: unless-stopped

volumes:
  zookeeper_data:
  kafka_data:
  postgres-data:
