// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/contextify.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContextifyService_Ping_FullMethodName = "/contextify.ContextifyService/Ping"
)

// ContextifyServiceClient is the client API for ContextifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContextifyServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type contextifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContextifyServiceClient(cc grpc.ClientConnInterface) ContextifyServiceClient {
	return &contextifyServiceClient{cc}
}

func (c *contextifyServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ContextifyService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextifyServiceServer is the server API for ContextifyService service.
// All implementations must embed UnimplementedContextifyServiceServer
// for forward compatibility.
type ContextifyServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedContextifyServiceServer()
}

// UnimplementedContextifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContextifyServiceServer struct{}

func (UnimplementedContextifyServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedContextifyServiceServer) mustEmbedUnimplementedContextifyServiceServer() {}
func (UnimplementedContextifyServiceServer) testEmbeddedByValue()                           {}

// UnsafeContextifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContextifyServiceServer will
// result in compilation errors.
type UnsafeContextifyServiceServer interface {
	mustEmbedUnimplementedContextifyServiceServer()
}

func RegisterContextifyServiceServer(s grpc.ServiceRegistrar, srv ContextifyServiceServer) {
	// If the following call pancis, it indicates UnimplementedContextifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContextifyService_ServiceDesc, srv)
}

func _ContextifyService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextifyServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContextifyService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextifyServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContextifyService_ServiceDesc is the grpc.ServiceDesc for ContextifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContextifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contextify.ContextifyService",
	HandlerType: (*ContextifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ContextifyService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/contextify.proto",
}
